// Code generated by hertz generator.

package handler

import (
	"context"
	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
	"p_meego/server/shared/errno"
)

// Ping .
func Ping(ctx context.Context, c *app.RequestContext) {
	resp := new(errno.Response)
	resp.Success("pong")
	c.JSON(consts.StatusOK, resp)
}
