// Code generated by hertz generator.

package main

import (
	"fmt"
	"github.com/cloudwego/hertz/pkg/app/server"
	hertztracing "github.com/hertz-contrib/obs-opentelemetry/tracing"
	"p_meego/server/cmd/api/config"
	"p_meego/server/cmd/api/initialize"
	"p_meego/server/cmd/api/initialize/thirdpart"
)

func main() {
	// 本地配置文件初始化
	initialize.InitLocalConfig()
	// 根据本地配置文件初始化日志
	initialize.InitLogger()
	// 根据本地配置文件初始化配置
	initialize.InitConfig()
	// 注册中心
	r, info := initialize.InitRegistry(config.GlobalServerConfig.Port)
	tracer, trcCfg := hertztracing.NewServerTracer()
	//  初始化第三方服务
	thirdpart.InitThirdPart()

	// create a new server
	h := server.New(
		tracer,
		server.WithALPN(true),
		server.WithHostPorts(fmt.Sprintf(":%d", config.GlobalServerConfig.Port)),
		server.WithRegistry(r, info),
		server.WithHandleMethodNotAllowed(true),
	)
	h.Use(hertztracing.ServerMiddleware(trcCfg))
	register(h)
	h.Spin()
}
